generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Signature
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: signature
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - dm_user_id
          - petition_id
          - collection_id
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - dm_user_id
          - petition_id
          - collection_id
          - created_at
      form:
        display:
          NONE: [dm_user_id, petition_id, collection_id]
        class: SignatureAdminForm
        fields: {  }
      edit: ~
      new: ~
