Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:

  Petition:

    petition:
      name:           Pétition
      components:
        list:
        show:

    action:

    collection:
      name:           Collecte

  Utilisateur:

    dmUser:
      name:           Utilisateur

    country:
      name:           Pays

  Site:

    partner:

    product:

    citation: