Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        nextAction:
        sitemap:
          cache:      true
        sharePage:
        topMenu:
          cache:      true

  Petition:

    petition:
      name:           Pétition
      page:           true
      components:
        list:
        showTitle:
          cache:      true
        showContent:
        showTopMenu:
          cache:      true

    action:
      components:
        list:

    collection:
      name:           Collecte
      page:           true
      parent:         petition
      components:
        show:

  Utilisateur:

    dmUser:
      name:           Utilisateur
      components:
        signupAction:
        unsuscribeLetter:

    inscription:
      components:
        presentation:
        creerCollecte:
        diffuser:
        recevoirCampagnes:
        soutenir:
        suivreActu:

    country:
      name:           Pays
      
    export:
      admin:          true

  Site:

    partner:
      name:           Partenaire

    product:
      name:           Produit

    citation:
      components:
        list:

    siteWidget:
      components:
        list:

  Tag:

    dmTag:
      page:           false