Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:
        nextAction:

  Petition:

    petition:
      name:           Pétition
      page:           true
      components:
        list:
        showTitle:
        showContent:

    action:

    collection:
      name:           Collecte

  Utilisateur:

    dmUser:
      name:           Utilisateur

    country:
      name:           Pays

  Site:

    partner:
      name:           Partenaire

    product:
      name:           Produit

    citation:
      components:
        list:         