parameters:

  email_sender.class:     myEmailSender

services:

  email_sender:
    class:                %email_sender.class%
    shared:               true
    arguments:            [ @service_container, @dispatcher ]