parameters:

  email_sender.class:     myEmailSender

  open_inviter.class:     dmOpenInviter

  bit_ly_api.login:       ornicar
  bit_ly_api.api_key:     R_fd1ff8d93e3a646717d98c37c7ecb307

services:

  email_sender:
    class:                %email_sender.class%
    shared:               true
    arguments:            [ @service_container, @dispatcher ]

  open_inviter:
    class:                %open_inviter.class%
    shared:               true
    arguments:            []