<?php

/**
 * BasePartnerPetition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $partner_id
 * @property integer $petition_id
 * @property Partner $Partner
 * @property Petition $Petition
 * 
 * @method integer         getPartnerId()   Returns the current record's "partner_id" value
 * @method integer         getPetitionId()  Returns the current record's "petition_id" value
 * @method Partner         getPartner()     Returns the current record's "Partner" value
 * @method Petition        getPetition()    Returns the current record's "Petition" value
 * @method PartnerPetition setPartnerId()   Sets the current record's "partner_id" value
 * @method PartnerPetition setPetitionId()  Sets the current record's "petition_id" value
 * @method PartnerPetition setPartner()     Sets the current record's "Partner" value
 * @method PartnerPetition setPetition()    Sets the current record's "Petition" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BasePartnerPetition extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner_petition');
        $this->hasColumn('partner_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}