<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $url
 * @property integer $image_id
 * @property string $text
 * @property Doctrine_Collection $Petitions
 * @property DmMedia $Image
 * @property Doctrine_Collection $ProductPetition
 * 
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method integer             getImageId()         Returns the current record's "image_id" value
 * @method string              getText()            Returns the current record's "text" value
 * @method Doctrine_Collection getPetitions()       Returns the current record's "Petitions" collection
 * @method DmMedia             getImage()           Returns the current record's "Image" value
 * @method Doctrine_Collection getProductPetition() Returns the current record's "ProductPetition" collection
 * @method Product             setTitle()           Sets the current record's "title" value
 * @method Product             setUrl()             Sets the current record's "url" value
 * @method Product             setImageId()         Sets the current record's "image_id" value
 * @method Product             setText()            Sets the current record's "text" value
 * @method Product             setPetitions()       Sets the current record's "Petitions" collection
 * @method Product             setImage()           Sets the current record's "Image" value
 * @method Product             setProductPetition() Sets the current record's "ProductPetition" collection
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseProduct extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'extra' => 'link',
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Petition as Petitions', array(
             'refClass' => 'ProductPetition',
             'local' => 'product_id',
             'foreign' => 'petition_id'));

        $this->hasOne('DmMedia as Image', array(
             'local' => 'image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ProductPetition', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}