<?php

/**
 * BaseCitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $text
 * @property clob $source
 * 
 * @method clob     getText()   Returns the current record's "text" value
 * @method clob     getSource() Returns the current record's "source" value
 * @method Citation setText()   Sets the current record's "text" value
 * @method Citation setSource() Sets the current record's "source" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseCitation extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('citation');
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             'notnull' => true,
             ));
        $this->hasColumn('source', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}