<?php

/**
 * BasePartenairePetition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $petition_id
 * @property integer $partenaire_id
 * @property Partenaire $Partenaire
 * @property Petition $Petition
 * 
 * @method integer            getPetitionId()    Returns the current record's "petition_id" value
 * @method integer            getPartenaireId()  Returns the current record's "partenaire_id" value
 * @method Partenaire         getPartenaire()    Returns the current record's "Partenaire" value
 * @method Petition           getPetition()      Returns the current record's "Petition" value
 * @method PartenairePetition setPetitionId()    Sets the current record's "petition_id" value
 * @method PartenairePetition setPartenaireId()  Sets the current record's "partenaire_id" value
 * @method PartenairePetition setPartenaire()    Sets the current record's "Partenaire" value
 * @method PartenairePetition setPetition()      Sets the current record's "Petition" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasePartenairePetition extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire_petition');
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('partenaire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partenaire', array(
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}