<?php

/**
 * BaseProductPetition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $petition_id
 * @property integer $product_id
 * @property Product $Product
 * @property Petition $Petition
 * 
 * @method integer         getPetitionId()  Returns the current record's "petition_id" value
 * @method integer         getProductId()   Returns the current record's "product_id" value
 * @method Product         getProduct()     Returns the current record's "Product" value
 * @method Petition        getPetition()    Returns the current record's "Petition" value
 * @method ProductPetition setPetitionId()  Sets the current record's "petition_id" value
 * @method ProductPetition setProductId()   Sets the current record's "product_id" value
 * @method ProductPetition setProduct()     Sets the current record's "Product" value
 * @method ProductPetition setPetition()    Sets the current record's "Petition" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseProductPetition extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_petition');
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}