<?php

/**
 * BaseSignature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_user_id
 * @property integer $petition_id
 * @property integer $collection_id
 * @property DmUser $User
 * @property Petition $Petition
 * @property Collection $Collection
 * 
 * @method integer    getDmUserId()      Returns the current record's "dm_user_id" value
 * @method integer    getPetitionId()    Returns the current record's "petition_id" value
 * @method integer    getCollectionId()  Returns the current record's "collection_id" value
 * @method DmUser     getUser()          Returns the current record's "User" value
 * @method Petition   getPetition()      Returns the current record's "Petition" value
 * @method Collection getCollection()    Returns the current record's "Collection" value
 * @method Signature  setDmUserId()      Sets the current record's "dm_user_id" value
 * @method Signature  setPetitionId()    Sets the current record's "petition_id" value
 * @method Signature  setCollectionId()  Sets the current record's "collection_id" value
 * @method Signature  setUser()          Sets the current record's "User" value
 * @method Signature  setPetition()      Sets the current record's "Petition" value
 * @method Signature  setCollection()    Sets the current record's "Collection" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseSignature extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('signature');
        $this->hasColumn('dm_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('collection_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('user_signed_petition', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
              1 => 'petition_id',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser as User', array(
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Collection', array(
             'local' => 'collection_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}