<?php

/**
 * BasePartenaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $url
 * @property integer $image_id
 * @property Doctrine_Collection $Petitions
 * @property Doctrine_Collection $PartenairePetition
 * 
 * @method string              getTitle()              Returns the current record's "title" value
 * @method string              getUrl()                Returns the current record's "url" value
 * @method integer             getImageId()            Returns the current record's "image_id" value
 * @method Doctrine_Collection getPetitions()          Returns the current record's "Petitions" collection
 * @method Doctrine_Collection getPartenairePetition() Returns the current record's "PartenairePetition" collection
 * @method Partenaire          setTitle()              Sets the current record's "title" value
 * @method Partenaire          setUrl()                Sets the current record's "url" value
 * @method Partenaire          setImageId()            Sets the current record's "image_id" value
 * @method Partenaire          setPetitions()          Sets the current record's "Petitions" collection
 * @method Partenaire          setPartenairePetition() Sets the current record's "PartenairePetition" collection
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasePartenaire extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'extra' => 'link',
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Petition as Petitions', array(
             'refClass' => 'PartenairePetition',
             'local' => 'partenaire_id',
             'foreign' => 'petition_id'));

        $this->hasMany('PartenairePetition', array(
             'local' => 'id',
             'foreign' => 'partenaire_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}