<?php

/**
 * BaseProduitPetition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $petition_id
 * @property integer $produit_id
 * @property Produit $Produit
 * @property Petition $Petition
 * 
 * @method integer         getPetitionId()  Returns the current record's "petition_id" value
 * @method integer         getProduitId()   Returns the current record's "produit_id" value
 * @method Produit         getProduit()     Returns the current record's "Produit" value
 * @method Petition        getPetition()    Returns the current record's "Petition" value
 * @method ProduitPetition setPetitionId()  Sets the current record's "petition_id" value
 * @method ProduitPetition setProduitId()   Sets the current record's "produit_id" value
 * @method ProduitPetition setProduit()     Sets the current record's "Produit" value
 * @method ProduitPetition setPetition()    Sets the current record's "Petition" value
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseProduitPetition extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('produit_petition');
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('produit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Produit', array(
             'local' => 'produit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}