<?php

/**
 * BaseCollection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_user_id
 * @property integer $petition_id
 * @property string $title
 * @property clob $text
 * @property integer $goal
 * @property string $hash_code
 * @property DmUser $User
 * @property Petition $Petition
 * @property Doctrine_Collection $Signature
 * 
 * @method integer             getDmUserId()    Returns the current record's "dm_user_id" value
 * @method integer             getPetitionId()  Returns the current record's "petition_id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getText()        Returns the current record's "text" value
 * @method integer             getGoal()        Returns the current record's "goal" value
 * @method string              getHashCode()    Returns the current record's "hash_code" value
 * @method DmUser              getUser()        Returns the current record's "User" value
 * @method Petition            getPetition()    Returns the current record's "Petition" value
 * @method Doctrine_Collection getSignature()   Returns the current record's "Signature" collection
 * @method Collection          setDmUserId()    Sets the current record's "dm_user_id" value
 * @method Collection          setPetitionId()  Sets the current record's "petition_id" value
 * @method Collection          setTitle()       Sets the current record's "title" value
 * @method Collection          setText()        Sets the current record's "text" value
 * @method Collection          setGoal()        Sets the current record's "goal" value
 * @method Collection          setHashCode()    Sets the current record's "hash_code" value
 * @method Collection          setUser()        Sets the current record's "User" value
 * @method Collection          setPetition()    Sets the current record's "Petition" value
 * @method Collection          setSignature()   Sets the current record's "Signature" collection
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseCollection extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collection');
        $this->hasColumn('dm_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('petition_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('goal', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 50,
             'unsigned' => true,
             ));
        $this->hasColumn('hash_code', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser as User', array(
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Signature', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}