<?php

/**
 * BaseProduit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $url
 * @property integer $image_id
 * @property string $texte
 * @property Doctrine_Collection $Petitions
 * @property DmMedia $Image
 * @property Doctrine_Collection $ProduitPetition
 * 
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method integer             getImageId()         Returns the current record's "image_id" value
 * @method string              getTexte()           Returns the current record's "texte" value
 * @method Doctrine_Collection getPetitions()       Returns the current record's "Petitions" collection
 * @method DmMedia             getImage()           Returns the current record's "Image" value
 * @method Doctrine_Collection getProduitPetition() Returns the current record's "ProduitPetition" collection
 * @method Produit             setTitle()           Sets the current record's "title" value
 * @method Produit             setUrl()             Sets the current record's "url" value
 * @method Produit             setImageId()         Sets the current record's "image_id" value
 * @method Produit             setTexte()           Sets the current record's "texte" value
 * @method Produit             setPetitions()       Sets the current record's "Petitions" collection
 * @method Produit             setImage()           Sets the current record's "Image" value
 * @method Produit             setProduitPetition() Sets the current record's "ProduitPetition" collection
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseProduit extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('produit');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'extra' => 'link',
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('texte', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Petition as Petitions', array(
             'refClass' => 'ProduitPetition',
             'local' => 'produit_id',
             'foreign' => 'petition_id'));

        $this->hasOne('DmMedia as Image', array(
             'local' => 'image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ProduitPetition', array(
             'local' => 'id',
             'foreign' => 'produit_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}