generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Collecte
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: collecte
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=title'
          - dm_user_id
          - petition_id
          - signature_list
          - text
          - objectif
          - hash_code
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - dm_user_id
          - petition_id
          - text
          - objectif
          - hash_code
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, dm_user_id, petition_id]
          Text: [text]
          Signatures: [signature_list]
          Others: [objectif, hash_code]
        class: CollecteAdminForm
        fields: {  }
      edit: ~
      new: ~
