generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Citation
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: citation
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - texte
          - source
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - texte
          - source
          - created_at
          - updated_at
      form:
        display:
          Texte: [texte]
          Source: [source]
        class: CitationAdminForm
        fields: {  }
      edit: ~
      new: ~
