generator:
  param:
    config:
      fields:
        is_active:
          label:  Traité
        body:
          label:  Message
        answer:
          label:  Répondre
      list:
        display:
          - '=name'
          - email
          - body
          - petition_id
          - is_active
          - _answer
          - created_at
      form:
        display:
          NONE: [name, email, petition_id, is_active, _answer]
          Body: [_message]