<?php

/**
 * Collecte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Collecte extends BaseCollecte
{
  
  public function preSave($event)
  {
    if(!$this->hashCode)
    {
      $this->hashCode = dmString::random(8);
    }

    return parent::preSave($event);
  }

}
