<?php

/**
 * Collection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
class Collection extends BaseCollection
{

  public function __toString()
  {
    return $this->get('Petition')->__toString().' par '.$this->get('User')->__toString();
  }

  public function getStyle()
  {
    return $this->get('Petition')->get('style');
  }

  public function getNbSignatures()
  {
    return dmDb::table('Signature')->countForCollectionAndPetition($this, $this->get('Petition'));
  }

  public function preInsert($event)
  {
    $this->hashCode = dmString::random(8);

    return parent::preInsert($event);
  }

  public function postInsert($event)
  {
    /*
     * Change the user signature to make it come from its collection
     */
    if($signature = dmDb::table('Signature')->findOneByUserAndPetition($this->User, $this->Petition))
    {
      $signature->collection_id = $this->id;
      $signature->save();
    }

    $this->getEventDispatcher()->notify(new sfEvent($this, 'collection.created'));

    return parent::postInsert($event);
  }

}
