<?php

/**
 * Petition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
class Petition extends BasePetition
{

  public function getNextAction()
  {
    return dmDb::query('Action a')
    ->whereIsActive()
    ->andWhere('a.petition_id = ?', $this->id)
    ->andWhere('a.begin_at IS NOT NULL')
    ->andWhere('a.begin_at > ?', date('Y-m-d H:i:s', time()))
    ->orderBy('a.begin_at ASC')
    ->fetchOne();
  }

}
