<?php

/**
 * Signature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
class Signature extends BaseSignature
{

  public function postInsert($event)
  {
    $this->getEventDispatcher()->notify(new sfEvent($this, 'signature.created'));

    return parent::postInsert($event);
  }

}
