generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Collection
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: collection
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - dm_user_id
          - petition_id
          - _goal
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - is_active
          - dm_user_id
          - petition_id
          - text
          - goal
          - hash_code
          - created_at
          - updated_at
      form:
        display:
          NONE: [dm_user_id, petition_id, is_active]
          Text: [text]
          Objectif: [_goal]
          Code: [hash_code]
        class: CollectionAdminForm
        fields: {  }
      edit: ~
      new: ~
