generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Petition
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: petition
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        signatories_list:
          label: Utilisateurs
        partners_list:
          label: Partners
        products_list:
          label: Products
        tags_list:
          label: Tags
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - collections_list
          - action_list
          - signatories_list
          - partners_list
          - products_list
          - tags_list
          - text
          - slogan
          - is_active
          - url_feed_actu
          - url_feed_communique
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - text
          - slogan
          - url_feed_actu
          - url_feed_communique
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Text: [text]
          Utilisateurs: [signatories_list]
          Tags: [tags]
          Collectes: [collections_list]
          Actions: [action_list]
          Others: [slogan, url_feed_actu, url_feed_communique]
        class: PetitionAdminForm
        fields:
          url_feed_actu: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          url_feed_communique: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
