generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Petition
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: petition
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        signatories_list:
          label: Utilisateurs
        partners_list:
          label: Partenaires
        products_list:
          label: Produits
        tags_list:
          label: Tags
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - collections_list
          - action_list
          - signatories_list
          - partners_list
          - products_list
          - tags_list
          - text
          - slogan
          - is_active
          - actu_page_url
          - actu_feed_url
          - facebook_page_url
          - twitter_page_url
          - communique_page_url
          - communique_feed_url
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - text
          - slogan
          - actu_page_url
          - actu_feed_url
          - facebook_page_url
          - twitter_page_url
          - communique_page_url
          - communique_feed_url
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Text: [text]
          Utilisateurs: [signatories_list]
          Partenaires: [partners_list]
          Produits: [products_list]
          Tags: [tags]
          Collectes: [collections_list]
          Actions: [action_list]
          Others: [slogan, actu_page_url, actu_feed_url, facebook_page_url, twitter_page_url, communique_page_url, communique_feed_url]
        class: PetitionAdminForm
        fields:
          actu_page_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          actu_feed_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          facebook_page_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          twitter_page_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          communique_page_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
          communique_feed_url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
