generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Petition
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: petition
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        signatories_list:
          label: Utilisateurs
        partners_list:
          label: Partenaires
        products_list:
          label: Produits
        tags_list:
          label: Tags
        is_active:
          label: Active
        signatories_list:
          label: Signatures
        collecte_motivation:
          help: "Argumentaire par défaut pour les nouvelles collectes"
        diffusion_message:
          help: "Message de diffusion par défaut (transfert de courriel et import facebook). La variable %url% représente la pétition ou la collecte."
      list:
        display:
          - '=title'
          - slogan
          - actions_list
          - nb_collections
          - nb_signatures
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - text
          - slogan
          - actu_page_url
          - actu_feed_url
          - facebook_page_url
          - twitter_page_url
          - communique_page_url
          - communique_feed_url
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active, slogan, style]
          Text: [resume, text]
          "Tags et actions": [tags, actions_list]
          "Signataires et collectes": [signatories_list, collections_list]
          "Partenaires et produits": [partners_list, products_list]
          "Actualités": [actu_page_url, actu_feed_url]
          "Communiqués": [communique_page_url, communique_feed_url]
          "Liens": [facebook_page_url, twitter_page_url]
          "Autres": [collecte_motivation, diffusion_message]
        class: PetitionAdminForm
        fields:
          actu_page_url: { is_link: true }
          actu_feed_url: { is_link: true }
          facebook_page_url: { is_link: true }
          twitter_page_url: { is_link: true }
          communique_page_url: { is_link: true }
          communique_feed_url: { is_link: true }
      edit: ~
      new: ~
