generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Partner
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: partner
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        petitions_list:
          label: Pétitions
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - image_id
          - petitions_list
          - url
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - url
          - image_id
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Image: [image_id_form, image_id_view]
          Pétitions: [petitions_list]
          Others: [url]
        class: PartnerAdminForm
        fields:
          url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
