<?php

/**
 * DmMediaFolder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class DmMediaFolder extends PluginDmMediaFolder
{
}
