default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - countdown
    - layout
    - main
    - text
    - markdown

  javascripts:
    - countdown/jquery.countdown.min
    - front

  has_layout:     true
  layout:         layout