default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - countdown
    - layout
    - main
    - text
    - markdown
    - citation

  javascripts:
    - cycle/jquery.cycle.lite.min
    - countdown/jquery.countdown.min
    - front

  has_layout:     true
  layout:         layout