generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: SiteWidget
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: site_widget
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - _code
          - text
          - is_active
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - is_active
          - text
          - code
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Text: [text]
          Code: [code, _code_preview]
        class: SiteWidgetAdminForm
        fields: {  }
      edit: ~
      new: ~
