<?php

/**
 * DmUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ape-petition
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class DmUser extends PluginDmUser
{

  public function preSave($event)
  {
    if(!$this->username)
    {
      $this->username = $this->email;
    }

    return parent::preSave($event);
  }
}
