<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dm_tag', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('produit', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'extra' => 'link',
              'length' => '255',
             ),
             'image_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'texte' => 
             array(
              'type' => 'string',
              'length' => '500',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('produit_petition', array(
             'petition_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'produit_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'petition_id',
              1 => 'produit_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('produit_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'extra' => 'link',
              'length' => '255',
             ),
             'image_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'texte' => 
             array(
              'type' => 'string',
              'length' => '500',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->changeColumn('partenaire', 'url', 'string', '255', array(
             'extra' => 'link',
             ));
        $this->changeColumn('petition', 'url_feed_actu', 'string', '255', array(
             'notnull' => '1',
             'extra' => 'link',
             ));
        $this->changeColumn('petition', 'url_feed_communique', 'string', '255', array(
             'notnull' => '1',
             'extra' => 'link',
             ));
        $this->changeColumn('partenaire_version', 'url', 'string', '255', array(
             'extra' => 'link',
             ));
        $this->changeColumn('petition_version', 'url_feed_actu', 'string', '255', array(
             'notnull' => '1',
             'extra' => 'link',
             ));
        $this->changeColumn('petition_version', 'url_feed_communique', 'string', '255', array(
             'notnull' => '1',
             'extra' => 'link',
             ));
    }

    public function down()
    {
        $this->dropTable('dm_tag');
        $this->dropTable('produit');
        $this->dropTable('produit_petition');
        $this->dropTable('produit_version');
    }
}