<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('petition_dm_tag', 'petition_dm_tag_dm_tag_id_dm_tag_id', array(
             'name' => 'petition_dm_tag_dm_tag_id_dm_tag_id',
             'local' => 'dm_tag_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_tag',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('petition_dm_tag', 'petition_dm_tag_id_petition_id', array(
             'name' => 'petition_dm_tag_id_petition_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('petition_dm_tag', 'petition_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->addIndex('petition_dm_tag', 'petition_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('petition_dm_tag', 'petition_dm_tag_dm_tag_id_dm_tag_id');
        $this->dropForeignKey('petition_dm_tag', 'petition_dm_tag_id_petition_id');
        $this->removeIndex('petition_dm_tag', 'petition_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->removeIndex('petition_dm_tag', 'petition_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}