<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('partenaire_petition', 'partenaire_petition_partenaire_id_partenaire_id', array(
             'name' => 'partenaire_petition_partenaire_id_partenaire_id',
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('partenaire_petition', 'partenaire_petition_petition_id_petition_id', array(
             'name' => 'partenaire_petition_petition_id_petition_id',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('partenaire_version', 'partenaire_version_id_partenaire_id', array(
             'name' => 'partenaire_version_id_partenaire_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('partenaire_petition', 'partenaire_petition_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
        $this->addIndex('partenaire_petition', 'partenaire_petition_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->addIndex('partenaire_version', 'partenaire_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('partenaire_petition', 'partenaire_petition_partenaire_id_partenaire_id');
        $this->dropForeignKey('partenaire_petition', 'partenaire_petition_petition_id_petition_id');
        $this->dropForeignKey('partenaire_version', 'partenaire_version_id_partenaire_id');
        $this->removeIndex('partenaire_petition', 'partenaire_petition_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
        $this->removeIndex('partenaire_petition', 'partenaire_petition_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->removeIndex('partenaire_version', 'partenaire_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}