<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('produit_petition', 'produit_petition_produit_id_produit_id', array(
             'name' => 'produit_petition_produit_id_produit_id',
             'local' => 'produit_id',
             'foreign' => 'id',
             'foreignTable' => 'produit',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('produit_petition', 'produit_petition_petition_id_petition_id', array(
             'name' => 'produit_petition_petition_id_petition_id',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('produit_version', 'produit_version_id_produit_id', array(
             'name' => 'produit_version_id_produit_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'produit',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('produit_petition', 'produit_petition_produit_id', array(
             'fields' => 
             array(
              0 => 'produit_id',
             ),
             ));
        $this->addIndex('produit_petition', 'produit_petition_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->addIndex('produit_version', 'produit_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('produit_petition', 'produit_petition_produit_id_produit_id');
        $this->dropForeignKey('produit_petition', 'produit_petition_petition_id_petition_id');
        $this->dropForeignKey('produit_version', 'produit_version_id_produit_id');
        $this->removeIndex('produit_petition', 'produit_petition_produit_id', array(
             'fields' => 
             array(
              0 => 'produit_id',
             ),
             ));
        $this->removeIndex('produit_petition', 'produit_petition_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->removeIndex('produit_version', 'produit_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}