<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('citation_version', 'citation_version_id_citation_id', array(
             'name' => 'citation_version_id_citation_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'citation',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('citation_version', 'citation_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('citation_version', 'citation_version_id_citation_id');
        $this->removeIndex('citation_version', 'citation_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}