<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('produit', 'produit_image_id_dm_media_id', array(
             'name' => 'produit_image_id_dm_media_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('produit', 'produit_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('produit', 'produit_image_id_dm_media_id');
        $this->removeIndex('produit', 'produit_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
    }
}