<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('dm_user_version');
        $this->removeColumn('dm_user', 'version');
    }

    public function down()
    {
        $this->createTable('dm_user_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'username' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'algorithm' => 
             array(
              'type' => 'string',
              'default' => 'sha1',
              'notnull' => '1',
              'length' => '128',
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'is_super_admin' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'last_login' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'country_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'profession' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'zip_code' => 
             array(
              'type' => 'string',
              'length' => '6',
             ),
             'street' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_letter_actu' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'is_letter_action' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'photo_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('dm_user', 'version', 'integer', '8', array(
             ));
    }
}