<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_contact', 'petition_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_contact', 'petition_id');
    }
}