<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('site_widget', 'title', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
        $this->addColumn('site_widget_version', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('site_widget', 'title');
        $this->removeColumn('site_widget_version', 'title');
    }
}