<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_sent_mail', 'to_email', 'string', '5000', array(
             ));
        $this->changeColumn('dm_mail_template_translation', 'to_email', 'string', '5000', array(
             ));
    }

    public function down()
    {

    }
}