<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('collection', 'collection_dm_user_id_dm_user_id');
        $this->dropForeignKey('collection', 'collection_petition_id_petition_id');
        $this->createForeignKey('collection', 'collection_dm_user_id_dm_user_id_1', array(
             'name' => 'collection_dm_user_id_dm_user_id_1',
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('collection', 'collection_petition_id_petition_id_1', array(
             'name' => 'collection_petition_id_petition_id_1',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('collection', 'collection_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->addIndex('collection', 'collection_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('collection', 'collection_dm_user_id_dm_user_id', array(
             'name' => 'collection_dm_user_id_dm_user_id',
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('collection', 'collection_petition_id_petition_id', array(
             'name' => 'collection_petition_id_petition_id',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->dropForeignKey('collection', 'collection_dm_user_id_dm_user_id_1');
        $this->dropForeignKey('collection', 'collection_petition_id_petition_id_1');
        $this->removeIndex('collection', 'collection_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->removeIndex('collection', 'collection_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
    }
}