<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('collection', 'title');
        $this->removeColumn('collection_version', 'title');
    }

    public function down()
    {
        $this->addColumn('collection', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('collection_version', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}