<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_user', 'is_letter_actu', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('dm_user', 'is_letter_action', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {

    }
}