<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_mail_template', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'debug_string', 'clob', '', array(
             ));
        $this->changeColumn('dm_sent_mail', 'title', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_sent_mail', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_sent_mail', 'from_email', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_sent_mail', 'to_email', 'string', '5000', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_mail_template', 'sender_email');
        $this->removeColumn('dm_sent_mail', 'cc_email');
        $this->removeColumn('dm_sent_mail', 'bcc_email');
        $this->removeColumn('dm_sent_mail', 'reply_to_email');
        $this->removeColumn('dm_sent_mail', 'sender_email');
        $this->removeColumn('dm_sent_mail', 'debug_string');
    }
}