<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_sent_mail', 'culture', 'string', '16', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_sent_mail', 'culture');
    }
}