<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'style', 'string', '128', array(
             'notnull' => '1',
             'default' => 'default',
             ));
        $this->addColumn('petition_version', 'style', 'string', '128', array(
             'notnull' => '1',
             'default' => 'default',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'style');
        $this->removeColumn('petition_version', 'style');
    }
}