<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_mail_template_translation', 'title', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_mail_template_translation', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_mail_template_translation', 'from_email', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_mail_template_translation', 'to_email', 'string', '5000', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}