<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_user', 'gender', 'enum', '', array(
             'values' => 
             array(
              0 => 'male',
              1 => 'female',
             ),
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_user', 'gender');
    }
}