<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('product', 'product_image_id_dm_media_id');
        $this->createForeignKey('partner', 'partner_image_id_dm_media_id', array(
             'name' => 'partner_image_id_dm_media_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('product', 'product_image_id_dm_media_id_1', array(
             'name' => 'product_image_id_dm_media_id_1',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('partner', 'partner_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
        $this->addIndex('product', 'product_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('product', 'product_image_id_dm_media_id', array(
             'name' => 'product_image_id_dm_media_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->dropForeignKey('partner', 'partner_image_id_dm_media_id');
        $this->dropForeignKey('product', 'product_image_id_dm_media_id_1');
        $this->removeIndex('partner', 'partner_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
        $this->removeIndex('product', 'product_image_id', array(
             'fields' => 
             array(
              0 => 'image_id',
             ),
             ));
    }
}