<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_mail_template', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'strategy', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'transport', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_mail_template', 'cc_email');
        $this->removeColumn('dm_mail_template', 'bcc_email');
        $this->removeColumn('dm_mail_template', 'reply_to_email');
        $this->removeColumn('dm_sent_mail', 'strategy');
        $this->removeColumn('dm_sent_mail', 'transport');
    }
}