<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('dm_sent_mail', 'name');
        $this->removeColumn('dm_sent_mail', 'header');
        $this->removeColumn('dm_sent_mail', 'description');
        $this->addColumn('dm_sent_mail', 'dm_mail_template_id', 'integer', '8', array(
             ));
        $this->addColumn('dm_sent_mail', 'title', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'body', 'clob', '', array(
             ));
        $this->addColumn('dm_sent_mail', 'from_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'to_email', 'string', '5000', array(
             ));
    }

    public function down()
    {
        $this->addColumn('dm_sent_mail', 'name', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'header', 'string', '60000', array(
             ));
        $this->addColumn('dm_sent_mail', 'description', 'string', '60000', array(
             ));
        $this->removeColumn('dm_sent_mail', 'dm_mail_template_id');
        $this->removeColumn('dm_sent_mail', 'title');
        $this->removeColumn('dm_sent_mail', 'body');
        $this->removeColumn('dm_sent_mail', 'from_email');
        $this->removeColumn('dm_sent_mail', 'to_email');
    }
}