<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('citation', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('partner', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('product', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('citation_version', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('partner_version', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('product_version', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('citation', 'is_active');
        $this->removeColumn('partner', 'is_active');
        $this->removeColumn('product', 'is_active');
        $this->removeColumn('citation_version', 'is_active');
        $this->removeColumn('partner_version', 'is_active');
        $this->removeColumn('product_version', 'is_active');
    }
}