<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_user', 'hash_code', 'string', '8', array(
             'notnull' => '1',
             'unique' => '1',
             ));
    }

    public function down()
    {

    }
}