<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dm_contact', 'dm_contact_petition_id_petition_id', array(
             'name' => 'dm_contact_petition_id_petition_id',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('dm_contact', 'dm_contact_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dm_contact', 'dm_contact_petition_id_petition_id');
        $this->removeIndex('dm_contact', 'dm_contact_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
    }
}