generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Partenaire
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: partenaire
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        petitions_list:
          label: Pétitions
      list:
        display:
          - '=title'
          - petitions_list
          - url
          - image_id
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - url
          - image_id
          - created_at
          - updated_at
      form:
        display:
          NONE: [title]
          Pétitions: [petitions_list]
          Others: [url, image_id]
        class: PartenaireAdminForm
        fields:
          url: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
